(deftheme iffsid "My color theme")

(custom-theme-set-faces
 'iffsid
 '(default ((t (:background "#101010" :foreground "#f8f8f8"))))
 ;; #a7a7a7
 '(cursor ((t (:background "#f8b044"))))
 '(region ((t (:background "#27292a"))))
 '(blue ((t (:foreground "blue"))))
 '(border-glyph ((t (nil))))
 '(buffers-tab ((t (:background "#141414" :foreground "#CACACA"))))
 '(font-lock-builtin-face ((t (:foreground "#5c99db"))))
 '(font-lock-comment-face ((t (:foreground "#cd4240"))))
 '(font-lock-constant-face ((t (:foreground "#CF6A4C"))))
 '(font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
 '(font-lock-function-name-face ((t (:foreground "#f6b913"))))
 '(font-lock-keyword-face ((t (:foreground "#50eafb"))))
 '(font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
 '(font-lock-reference-face ((t (:foreground "SlateBlue"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "red"))))
 '(font-lock-string-face ((t (:foreground "#cdc36b"))))
 '(font-lock-type-face ((t (:foreground "#946d54"))))
 '(font-lock-variable-name-face ((t (:foreground "#efefec"))))
 '(font-lock-warning-face ((t (:foreground "red"))))
 '(minibuffer-prompt ((t (:foreground "#CACACA")))) ;#7F5F60
 '(ido-subdir ((t (:foreground "#CF6A4C"))))
 '(ido-first-match ((t (:foreground "#8F9D6A"))))
 '(ido-only-match ((t (:foreground "#8F9D6A"))))
 '(mumamo-background-chunk-submode ((t (:background "#222222"))))
 '(gui-element ((t (:background "#D4D0C8" :foreground "black"))))
 '(region ((t (:background "#27292A"))))
 '(mode-line ((t (:foreground "#000000" :background "#d48a11"))))
 '(mode-line-inactive ((t (:foreground "#000000" :background "#9a8037"))))
 '(mode-line-buffer-id ((t (:bold t :foreground "#000000" :background nil))))
 '(highlight ((t (:background "#111111"))))
 '(highline-face ((t (:background "SeaGreen"))))
 '(left-margin ((t (nil))))
 '(text-cursor ((t (:background "yellow" :foreground "black"))))
 '(toolbar ((t (nil))))
 '(underline ((nil (:underline nil))))
 '(zmacs-region ((t (:background "snow" :foreground "blue")))))

(provide-theme 'iffsid)
